CREATE DATABASE IF NOT EXISTS rectangulos_db;
USE rectangulos_db;

CREATE TABLE IF NOT EXISTS rectangulos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lado1 DECIMAL(10, 2) NOT NULL,
  lado2 DECIMAL(10, 2) NOT NULL,
  perimetro DECIMAL(10, 2) NOT NULL,
  superficie DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);